# src/config/example_database_data.yaml
tables:
  - name: roles
    columns:
      - name: id
        type: int
        primary_key: true
      - name: role_name
        type: string
  - name: users
    columns:
      - name: id
        type: int
        primary_key: true
      - name: name
        type: string
      - name: email
        type: string
      - name: password
        type: string
      - name: created_at
        type: datetime
      - name: role
        type: int
        foreign_key:
          table: roles
          column: id
  - name: collaborators
    columns:
      - name: id
        type: int
        primary_key: true
      - name: firstname
        type: string
      - name: lastname
        type: string
      - name: phone
        type: string
      - name: department
        type: string        
      - name: job_name
        type: string
      - name: manager
        type: string
      - name: annual_salary
        type: float


data:
  - table: users
    rows:
      - id: 1
        name: 'John Doe'
        email: 'john@doe.com'
        password: '$argon2id$v=19$m=32768,t=4,p=4$b611TolR6l1r7T2n1FoLYQ$7cyWhgYd4eJMoUR7XsCOo9xbPFHbclGw3sv2bGqY5es'
        created_at: '2025-03-20'
        role: 1
      - id: 2
        name: 'admin'
        email: 'admin@apisec.com'
        password: '$argon2id$v=19$m=32768,t=4,p=4$49x7z3nv/T/n/B9DSKk1Bg$xcVoanUP8mbfEyF3VWnd8dL1RTlPHaRQCUgVbTDI5oE'
        created_at: '2025-03-20'
        role: 9
  - table: roles
    rows:
      - id: 9
        role_name: admin
      - id: 1
        role_name: user
  - table: collaborators
    rows:
      - id: 1
        firstname: John
        lastname: Doe
        phone: 555-555-555
        department: HR
        job_name: HHR
        manager: 3
        annual_salary: 50000
      - id: 2
        firstname: Edward
        lastname: Clerc
        phone: 255-555-555
        department: IT
        job_name: help_desk
        manager: 6
        annual_salary: 37500
      - id: 3
        firstname: April
        lastname: Sanders
        phone: 344-555-555
        department: Marketing
        job_name: ad
        manager: 4
        annual_salary: 44000

