tables:
  - name: users
    columns:
      - name: id
        type: int
        primary_key: true
      - name: name
        type: string
      - name: email
        type: string
      - name: password
        type: string
      - name: created_at
        type: datetime
      - name: rple
        type: int

data:
  - table: users
    rows:
      - id: 1
        name: 'John Doe'
        email: '